config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :listings

  root to: "listings#home"

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :user
	validates :price, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }, :numericality => {:greater_than_or_equal_to => 0.01}

	# def self.approved
	# 	where(:approved => true)
	# end

	# def self.admin_view
	# 	Listing.all.order('price > 200 and approved = false').reverse.paginate(:page => params[:page], :per_page => 2)

	# end

	# def self.user_view
	# 	Listing.where('price < 200.00 or approved = true').order('name')
	# end

	def self.search(search)
		if search
    		where('name ILIKE ?', "%#{search}%")
 		else
    		all
  		end
	end

	# def self.owned
	# 	Listing.where('user_id = current_user.id')
	# end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :listings

  validates_uniqueness_of :nickname, :steam_id, :paypal
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:nickname, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:steam_id, :paypal, :email, :password, :password_confirmation, :current_password, :comments, :trust)
    end
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:home, :index]

  respond_to :html,:js 
  def home

  end
  # GET /listings
  # GET /listings.json
  def index
    if current_user == nil
      @listings = Listing.where('price < 200.00 or approved = true').search(params[:search]).paginate(:page => params[:page], :per_page => 9).order('created_at DESC')
    elsif current_user.admin?
      @listings = Listing.order('price DESC').search(params[:search]).paginate(:page => params[:page])
    elsif (params[:own]) == "true"
      @listings = Listing.where(:user => current_user).paginate(:page => params[:page])
    else
      @listings = Listing.where('price < 200.00 or approved = true').search(params[:search]).order('created_at DESC').paginate(:page => params[:page], :per_page => 9)
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
    if current_user == @listing.user or current_user.admin?
      @listing = Listing.find(params[:id])
    else redirect_to listings_path
    end
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    if current_user.trust?
      @listing.approved = true
    end
    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    if current_user == @listing.user
      @listing.destroy
    end
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :quality, :desc, :picture, :game, :price, :user_id, :approved)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand" href="#">
        <img alt="steamoutlet" src="/assets/logo.jpg">
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
        <li><a href="/listings">Listings</a></li>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li> -->
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %></a>
          <ul class="dropdown-menu" role="menu">
          <li><%= link_to '<span class="glyphicon glyphicon-cog"></span> Edit profile'.html_safe, edit_user_registration_path, :class => 'navbar-link' %></li>
          <li><%= link_to '<span class="glyphicon glyphicon-th-large"></span> My listings'.html_safe, listings_path(own: "true"), :class => 'navbar-link' %></li>
          <li class="divider"></li>
          <li><%= link_to '<span class="glyphicon glyphicon-off"></span> Logout'.html_safe, destroy_user_session_path, method: :delete, :class => 'navbar-link'  %><li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
          <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Steam</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navigation' %>

<center>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
</center>

<%= yield %>

</body>
</html>

app/views/listings/_form.html.erb
<%= form_for @listing do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quality %><br>
    <%= f.text_field :quality %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :desc, size: "48x12" %>
  </div>
  <div class="field">
    <%= f.label :picture_URL %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :game %><br>
    <%= f.text_field :game %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <% if current_user.admin? %>
  <div class="field">
    <%= f.label :approved %><br>
    <%= f.select :trust, ['true', 'false'] %>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/_listings.html.erb
<% @listings.each do |listing| %>
<div class="col-md-4" id="listings" align="middle">
  <div class="row">
    <%= link_to image_tag(listing.picture, class: "img-responsive aspect"), listing %>
    <div class="row">
      <%= listing.name %>
    </div>
    <div class="row"><br>
      <div class="col-md-4 col-md-offset-2">
        <%= listing.game %>
      </div>
      <div class="col-md-4">

        <%= link_to edit_listing_path(listing), class: "btn btn-sm btn-info" do %>
          <i class="glyphicon glyphicon-shopping-cart"><%= number_to_currency(listing.price, precision: 2) %>
          <% if listing.approved? %>
              <span class="glyphicon glyphicon-ok"></span>
            <% end %></i>
        <% end %>
      </div>
    </div>
  </div>




</div>
<% end %>

app/views/listings/edit.html.erb
<center><h1>Editing <%= @listing.name %></h1>

<%= render 'form' %>

<button type="button" class="btn btn-edit"><%= link_to '<span class="glyphicon glyphicon-list-alt"></span> View this listing'.html_safe, @listing %></button>
  <% if current_user == @listing.user or current_user.admin? %>
  <button type="button" class="btn btn-warning"><%= link_to '<span class="glyphicon glyphicon-list"></span> Back to listings'.html_safe, listings_path %></button>
  <button type="button" class="btn btn-md btn-hover btn-danger"><%= link_to '<span class="glyphicon glyphicon-trash"></span> Destroy'.html_safe, @listing, method: :delete, data: { confirm: 'Are you sure?' } %></button>
  <% end %></center>

app/views/listings/home.html.erb
<center>

<img src = "http://www.journaldugeek.com/files/2013/06/rickroll.gif"><br>

<h3>Lettin' off some steam</h3>

SteamOutl.et is currently in pre-ALPHA, devtest by invite only.
<br><br><br>
<button type="button" class="btn btn-sm btn-edit">
	<a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">
<span class="glyphicon glyphicon-shopping-cart"></span> Buy an invite today!</a>
</button>
</center>

<div style="position: relative">
      <p style="position: fixed; bottom: 0; width:100%; text-align: right"><small>©®™ Joel.</small></p>
</div>

app/views/listings/index.html.erb
<center><font size="8"><%= @listings.count %> listings</font>

<%= link_to new_listing_path, class: "btn btn-xs btn-default" do %>
<i class="glyphicon glyphicon-plus">New</i>
<% end %>


<body>
    <%= form_tag listings_path, remote: true, :method => 'get', :id => "listings_search" do %><br>
      <p style="direction: rtl;">
        <%= text_field_tag :search, params[:search], :placeholder => "Search listings" %>
        <% submit_tag "Search", :name => nil, :id => "search_btn" %>
      </p>
    <% end %>
    <%= will_paginate @listings %>
  </center>

<div id="main-container" class="container-fluid">
  <div class="row" id="listings_search">
  <%= render partial: 'listings' %>
</div>

</div>
</div>


<!--     <div id="main-container" class="container-fluid">
      <div class="row">
        <div id="content" class="col-xs-offset-4 col-xs-4">
        <%= form_tag listings_path, remote: true, :method => 'get', :id => "listings_search" do %>
          <p>
            <%= text_field_tag :search, params[:search], :placeholder => "Item search" %>
            <%= submit_tag "Search", :name => nil, :id => "search_btn" %>
          </p>
          <div id="listings">< render 'listings' %></div>
        <% end %>
        </div>
      </div>
    </div> -->

<script>
$("#search").keyup(function () {
     $.get($("#listings_search").attr("action"), $("#listings_search").serialize(), null, "script");
}
  );
</script>

</body>
<br>

app/views/listings/index.js.erb
$("#main-container").html("<%= escape_javascript(render("listings")) %>");

app/views/listings/new.html.erb
<center><h1>New listing</h1>

<%= render 'form' %>

<button type="button" class="btn btn-warning"><%= link_to '<span class="glyphicon glyphicon-list"></span> Back to listings'.html_safe, listings_path %></button></center>

app/views/listings/show.html.erb
<div id="show-container" class="container-fluid" align="middle">
  <div class="row">
    <div class="btn-success"><h2><%= @listing.name %></h2></div>
    <div class="col-md-4"><%= image_tag @listing.picture %>
    </div>
    <div class="col-md 6" style="vertical-align:middle"><br><br><br><br><br>
      <div><strong>Game:</strong> <%= @listing.game %></div>
      <div><strong>Quality:</strong> <%= @listing.quality %></div>
      <div><strong>Desc:</strong> <%= @listing.desc %></div>
      <div><strong>Price:</strong> <%= number_to_currency(@listing.price, precision: 2) %></div>
      <div><strong>Seller:</strong> <%= @listing.user.nickname %></div>
    </div>
  </div>
</div>

<center>
  <button type="button" class="btn btn-edit"><%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, listings_path %></button>
  <% if current_user == @listing.user or current_user.admin? %>
  <button type="button" class="btn btn-warning"><%= link_to '<span class="glyphicon glyphicon-list"></span> Edit'.html_safe, edit_listing_path(@listing) %></button>
  <button type="button" class="btn btn-md btn-hover btn-danger"><%= link_to '<span class="glyphicon glyphicon-trash"></span> Destroy'.html_safe, @listing, method: :delete, data: { confirm: 'Are you sure?' } %></button>
  <% end %>
</center>